vich_uploader:
    db_driver: orm

    mappings:
        avatar:
            uri_prefix: '%app.path.avatar%'
            upload_destination: '%kernel.project_dir%/public/images/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
